name: Tests familly project

on:
    [push, pull_request]

defaults:
  run:
    # The slightly odd shell call is to force bash to read .bashrc, which is
    # necessary for having conda behave sensibly.
    shell: bash -l -e {0}

jobs:
  tests:
    name: ${{ matrix.repo }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [qutip-qip, qutip-jax, qutip-qoc]
        version: [dev, release]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Install QuTiP and dependencies
        run: |
          # Install the extra requirement
          python -m pip install pytest pytest-rerunfailures  # tests
          python -m pip install numpy scipy cython filelock
          python -m pip install -e . -v --no-build-isolation

      - name: Install qutip-plugin
        run: |
          if [[ $matrix.version == "dev" ]]; then
            python -m pip install git+https://github.com/qutip/${{ matrix.repo }}.git
          else
            python -m pip install ${{ matrix.repo }}
          fi

      - name: Print python environment
        run: |
          pip list

      - name: Run test
        run: |
          cd ..
          pytest ${{ matrix.repo }}
